### ISSUE TITLE
Migrate data from old projects

### ISSUE THREAD

**Issue by RubenMattan** [our-city-app/plugin-trash-calendar#11]
### Why 
We have too many projects to monitor

### Projects that need to be migrated:
- [x] rogerthat-be-neerpelt-trash
- [x] rt-limburg-net-trash
- [x] ivvo-afval-kalender
- [x] ivvo-afval-kalender-diksmuide
- [x] ivvo-afval-kalender-lo-reninge

### How
- Create an export for every project given a sik key
- Create an import function in this project that asks for an url + sik

### Exported data / user should look like this.
- email unicode
- app_id unicode
- service_identity unicode
- location
  - address unicode
  - street
    - number integer
    - name unicode
  - house
    - number integer
    - bus unicode
- notifications [unicode]
- user_data_epoch integer
- next_collection integer

**Comment by lucasvanhalst** [comment]
To clarify, one of our projects racked up a non-insignificant bill because it had 130K tasks in its taskqueue because we didn't look at it for a long time

**Comment by RubenMattan** [comment]
Some other issues, this projects saves notifications on name instead of an id. This needs to be fixed.
- Update ActivityTO(number, name) to (key, name)
- Update all brandings to use key instead of name
- Update all user data

**Comment by abom** [comment]
@RubenMattan Don't see exactly where is the problem of saving notifications by name.
In older project, it stores it by ID, because IDs were the same across the same backend.
We couldn't find a good way to every backend activity to the same IDs.

**Comment by RubenMattan** [comment]
Can be that there will be backends where key and name will be the same, but if a backend supports  and ID we should use that one. Names can always change...

**Comment by abom** [comment]
Regarding activities, i thought of a more robust solution to make configurable, so activity name or id/key provided by backend can be mapped to our set of activities.

**Comment by abom** [comment]
@RubenMattan Ids can change too, and as it's specific to backend and it's hard to map them to our own set of activities, we can use names.

Using names is a generic solution for all backends, using ids will make us map this ids to get the names when the user enable/disable notifications, and this mapping can fail in case names/ids have changed.

**Comment by RubenMattan** [comment]
- projects with backend type limburg are migrated.
- projects with backend type ivvo on hold until they fix there api
